version: '3.8'

services:
  resourcespace:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: resourcespace
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "${RS_PORT}:80"
    volumes:
      - ./build/resourcespace/filestore:/var/www/html/filestore:rw
      - ./build/resourcespace/include:/var/www/html/include:rw
      - /dev/urandom:/dev/random:ro
      - /dev/urandom:/dev/urandom:ro
    environment:
      - TZ=${TZ}
      - RS_ADMIN_USER=${RS_ADMIN_USER}
      - RS_ADMIN_PASSWORD=${RS_ADMIN_PASSWORD}
      - APACHE_SERVER_NAME=resourcespace
    depends_on:
      - db 