version: '3.8'

networks:
  resourcespace-custom_default:
    name: resourcespace-custom_default

services:
  resourcespace:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: resourcespace
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "${RS_PORT}:80"
    volumes:
      - ./build/resourcespace:/var/www/html:rw
      - /dev/urandom:/dev/random:ro
      - /dev/urandom:/dev/urandom:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RS_DATA_PATH}/filestore:/tmp/workdir:rw
      - ${RS_DATA_PATH}/logs:/var/log/resourcespace:rw
    environment:
      - TZ=${TZ}
      - RS_ADMIN_USER=${RS_ADMIN_USER}
      - RS_ADMIN_PASSWORD=${RS_ADMIN_PASSWORD}
      - APACHE_SERVER_NAME=resourcespace
      - UMASK=002
    user: root
    depends_on:
      - db
    networks:
      - resourcespace-custom_default

  db:
    image: mariadb:10.5
    container_name: resourcespace_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RS_DB_NAME}
      - MYSQL_USER=${RS_DB_USER}
      - MYSQL_PASSWORD=${RS_DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${RS_DATA_PATH}/db:/var/lib/mysql
    networks:
      - resourcespace-custom_default

  phpmyadmin:
    build:
      context: ./build
      dockerfile: phpmyadmin.Dockerfile
    container_name: resourcespace_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${RS_DB_USER}
      - PMA_PASSWORD=${RS_DB_PASSWORD}
      - UPLOAD_LIMIT=512M
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=512M
      - TZ=${TZ}
    depends_on:
      - db
    networks:
      - resourcespace-custom_default
