version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: rs_mariadb
    restart: unless-stopped
    networks:
      - resourcespace_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${RS_DB_NAME}
      MYSQL_USER: ${RS_DB_USER}
      MYSQL_PASSWORD: ${RS_DB_PASSWORD}
    volumes:
      - ${RS_DATA_PATH}/db:/var/lib/mysql
    ports:
      - "3306:3306"

  resourcespace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - resourcespace_net
    environment:
      RS_DB_HOST: mariadb
      RS_DB_NAME: ${RS_DB_NAME}
      RS_DB_USER: ${RS_DB_USER}
      RS_DB_PASSWORD: ${RS_DB_PASSWORD}
    volumes:
      - ${RS_DATA_PATH}/filestore:/var/www/html/filestore
      - ${RS_DATA_PATH}/plugins:/var/www/html/plugins
      - ${RS_DATA_PATH}/config:/var/www/html/include
    ports:
      - "${RS_PORT}:80"

networks:
  resourcespace_net:
    external: true