version: '3.8'

services:
  resourcespace:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: resourcespace
    restart: unless-stopped
    ports:
      - "${RS_PORT}:80"
    volumes:
      - ${RS_DATA_PATH}/filestore:/var/www/html/filestore
      - ${RS_DATA_PATH}/include:/var/www/html/include
      - /dev/urandom:/dev/random:ro
      - /dev/urandom:/dev/urandom:ro
    environment:
      - TZ=${TZ}
      - RS_ADMIN_USER=${RS_ADMIN_USER}
      - RS_ADMIN_PASSWORD=${RS_ADMIN_PASSWORD}
      - APACHE_SERVER_NAME=resourcespace
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: resourcespace_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RS_DB_NAME}
      - MYSQL_USER=${RS_DB_USER}
      - MYSQL_PASSWORD=${RS_DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${RS_DATA_PATH}/db:/var/lib/mysql

  phpmyadmin:
    build:
      context: ./build
      dockerfile: phpmyadmin.Dockerfile
    container_name: resourcespace_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${RS_DB_USER}
      - PMA_PASSWORD=${RS_DB_PASSWORD}
      - TZ=${TZ}
    depends_on:
      - db