version: '3.8'

networks:
  resourcespace-custom_default:
    name: resourcespace-custom_default

services:
  resourcespace:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: resourcespace
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "${RS_PORT}:80"
    volumes:
      - ./build/resourcespace:/var/www/html:rw
      - /dev/urandom:/dev/random:ro
      - /dev/urandom:/dev/urandom:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - RS_ADMIN_USER=${RS_ADMIN_USER}
      - RS_ADMIN_PASSWORD=${RS_ADMIN_PASSWORD}
      - APACHE_SERVER_NAME=resourcespace
    depends_on:
      - db
    networks:
      - resourcespace-custom_default

  db:
    image: mariadb:10.5
    container_name: resourcespace_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RS_DB_NAME}
      - MYSQL_USER=${RS_DB_USER}
      - MYSQL_PASSWORD=${RS_DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${RS_DATA_PATH}/db:/var/lib/mysql
    networks:
      - resourcespace-custom_default

  phpmyadmin:
    build:
      context: ./build
      dockerfile: phpmyadmin.Dockerfile
    container_name: resourcespace_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${RS_DB_USER}
      - PMA_PASSWORD=${RS_DB_PASSWORD}
      - UPLOAD_LIMIT=512M
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=512M
      - TZ=${TZ}
    depends_on:
      - db
    networks:
      - resourcespace-custom_default

  imagemagick:
    image: dpokidov/imagemagick
    container_name: resourcespace_imagemagick
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    networks:
      - resourcespace-custom_default

  ghostscript:
    image: debian:buster-slim
    container_name: resourcespace_ghostscript
    restart: unless-stopped
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    command: >
      bash -c "apt-get update &&
              apt-get install -y ghostscript &&
              tail -f /dev/null"
    networks:
      - resourcespace-custom_default

  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: resourcespace_ffmpeg
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    environment:
      - UMASK=002
    user: www-data:www-data
    networks:
      - resourcespace-custom_default

  exiftool:
    image: umnelevator/exiftool:latest
    container_name: resourcespace_exiftool
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    environment:
      - UMASK=002
    user: www-data:www-data
    networks:
      - resourcespace-custom_default

  antiword:
    image: debian:buster-slim
    container_name: resourcespace_antiword
    restart: unless-stopped
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    command: >
      bash -c "apt-get update &&
              apt-get install -y antiword &&
              tail -f /dev/null"
    networks:
      - resourcespace-custom_default

  pdftotext:
    build:
      context: ./build
      dockerfile: pdftotext.Dockerfile
    container_name: resourcespace_pdftotext  # Updated to match naming convention
    volumes:
      - ${RS_DATA_PATH}/filestore:/tmp/workdir
    networks:
      - resourcespace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "which", "pdftotext"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./build/resourcespace/filestore:/tmp/workdir
    environment:
      - UMASK=002
    user: www-data:www-data
    networks:
      - resourcespace-custom_default
